//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesGeoInfo
    {
        public int SaleId { get; set; }
        public System.DateTime AcceptedDate { get; set; }
        public int dealerId { get; set; }
        public string CostumerAddress { get; set; }
        public int CarLineId { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
    }
}
