//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseFSWTester
{
    using System;
    using System.Collections.Generic;
    
    public partial class AOR
    {
        public int AORId { get; set; }
        public int Dealer_IdResponsable { get; set; }
        public string AORName { get; set; }
        public Nullable<int> CurrentPopulation { get; set; }
        public Nullable<int> C5YrsProyectedPopulation { get; set; }
        public Nullable<int> CurrentHouseholds { get; set; }
        public Nullable<int> C5YrsProyectedHouseholds { get; set; }
        public Nullable<int> CurrentHouseholdsUnder50 { get; set; }
        public Nullable<int> C5YrsProyectedHouseholdsUnder50 { get; set; }
        public Nullable<int> CurrentHouseholds50to100 { get; set; }
        public Nullable<int> C5YrsProyectedHouseholds50to100 { get; set; }
        public Nullable<int> CurrentHouseholdsOver100 { get; set; }
        public Nullable<int> C5YrsProyectedHouseholdsOver100 { get; set; }
    }
}
