//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseFSWTester
{
    using System;
    using System.Collections.Generic;
    
    public partial class CrossSellZip
    {
        public int CrossSellZip_id { get; set; }
        public int dealer_id { get; set; }
        public System.DateTime SalesFrom { get; set; }
        public System.DateTime SalesThrough { get; set; }
        public Nullable<int> SalesinZIP { get; set; }
        public Nullable<decimal> pctTotalSales { get; set; }
        public string ZIP { get; set; }
        public string ZIPName { get; set; }
        public Nullable<int> CurrentPopulation { get; set; }
        public Nullable<int> C5YrsProyectedPopulation { get; set; }
        public Nullable<int> CurrentHouseholds { get; set; }
        public Nullable<int> C5YrsProyectedHouseholds { get; set; }
        public Nullable<decimal> CurrentMediaHouseholdsIncome { get; set; }
        public Nullable<decimal> C5YrsMediaHouseholdsIncome { get; set; }
        public Nullable<decimal> CurrentAVGHouseholdsIncome { get; set; }
        public Nullable<decimal> C5YrsAVGHouseholdsIncome { get; set; }
        public Nullable<int> CurrentHouseholdsUnder50 { get; set; }
        public Nullable<int> C5YrsProyectedHouseholdsUnder50 { get; set; }
        public Nullable<int> CurrentHouseholds50to100 { get; set; }
        public Nullable<int> C5YrsProyectedHouseholds50to100 { get; set; }
        public Nullable<int> CurrentHouseholdsOver100 { get; set; }
        public Nullable<int> C5YrsProyectedHouseholdsOver100 { get; set; }
    }
}
