//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseFSWTester
{
    using System;
    using System.Collections.Generic;
    
    public partial class DWT_Dealers
    {
        public int DWT_DealerId { get; set; }
        public string Code { get; set; }
        public string NameShort { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string ZipNumber { get; set; }
        public string State { get; set; }
        public string ShippingZone { get; set; }
        public string Status { get; set; }
        public Nullable<int> District { get; set; }
        public string DistrictManager { get; set; }
        public Nullable<decimal> RetailLabor { get; set; }
        public Nullable<decimal> WarrantyLabor { get; set; }
        public string Website { get; set; }
        public int DealerId { get; set; }
    }
}
