//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseFSWTester
{
    using System;
    using System.Collections.Generic;
    
    public partial class RetailComparison
    {
        public int RetailComparison_id { get; set; }
        public int Dealer_id { get; set; }
        public Nullable<int> district { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public Nullable<int> Whlse_currentMY { get; set; }
        public Nullable<int> Whlse_passMY { get; set; }
        public Nullable<int> Whlse_ChangeYOY { get; set; }
        public Nullable<decimal> Pct_WhlseYOY { get; set; }
        public Nullable<int> Whlse_CurrenMonth { get; set; }
        public Nullable<int> RtlSls_currentMY { get; set; }
        public Nullable<int> RtlSls_passMY { get; set; }
        public Nullable<int> RtlSls_ChangeYOY { get; set; }
        public Nullable<decimal> Pct_RtlSlsYOY { get; set; }
        public Nullable<int> RtlSls_CurrenMonth { get; set; }
    }
}
