//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseFSWTester
{
    using System;
    using System.Collections.Generic;
    
    public partial class WareHouseReceipt
    {
        public int WareHouseReceipt_id { get; set; }
        public System.DateTime DateFile { get; set; }
        public string Activity { get; set; }
        public string ItemNumber { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string SDNNumber { get; set; }
        public string PONumber { get; set; }
        public string WH { get; set; }
        public string Picker { get; set; }
        public string PageNumber { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<System.DateTime> dateUpdatePrice { get; set; }
    }
}
